services:
  postgres:
    image: postgres:15-alpine

    container_name: fifa_team_hub_db

    restart: unless-stopped

    environment:

      POSTGRES_DB: fifa_team_hub
      POSTGRES_USER: fifa_user
      POSTGRES_PASSWORD: fifa_password

    ports:
      - "15432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    

  # --- SERVIÇO DO BACKEND ---
  backend:
    build: ./backend 
    container_name: fifa_backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - ./backend:/app 
    depends_on:
      postgres:
        condition: service_healthy 



  # --- SERVIÇO DO FRONTEND ---
  frontend:
    build: ./frontend 
    container_name: fifa_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - .env



volumes:
  postgres_data: