from enum import Enum

class UserRole(str,Enum):
    ATHELETE = "ATHELETE"
    AUDITOR = "AUDITOR"
    TECHNICAL_STAFF = "TECHNICAL_STAFF"
    gitr = "MEDICAL_STAFF"
    ORGANIZER = "ORGANIZER"

class TypeDocument(str,Enum):
    PASSPORT = "PASSPORT"
    CONVOCADO = "CONVOCADO"
    LAUDO_MEDICO = "LAUDO_MEDICO"
    RELATORIO_TATICO = "RELATORIO_TATICO"
    ESQUEMA_JOGADAS = "ESQUEMA_JOGADAS"

class LogAction(str,Enum):
    LOGIN = "LOGIN"
    LOGOUT = "LOGOUT"
    DELETE = "DELETE"
    UPLOAD = "UPLOAD"
    DOWNLOAD = "DOWNLOAD"
    ACCESS_DENIED = "ACCESS_DENIED"
    REGISTER_APPROVED = "REGISTER_APPROVED"
    REGISTER_REJECTED = "REGISTER_REJECTED"


class DocStatus(str,Enum):

    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"


class RegistrationStatus(str, Enum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
