"""tornar_selection_id_opcional_no_documento

Revision ID: 0dff16528721
Revises: 0fe7040c5c5d
Create Date: 2026-06-16 20:06:43.744336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0dff16528721'
down_revision = '0fe7040c5c5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.alter_column('selection_id',
               existing_type=sa.UUID(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.alter_column('selection_id',
               existing_type=sa.UUID(),
               nullable=False)

    # ### end Alembic commands ###
