"""adicionando status

Revision ID: 0fe7040c5c5d
Revises: 079ad6725475
Create Date: 2026-06-16 19:48:46.534183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fe7040c5c5d'
down_revision = '079ad6725475'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('details', sa.Text(), nullable=True))

    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.drop_column('status')

    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_column('details')

    # ### end Alembic commands ###
