"""add storage_path to document

Revision ID: 439b6c5d42ce
Revises: a51c203a158f
Create Date: 2026-07-07 22:13:02.091007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '439b6c5d42ce'
down_revision = 'a51c203a158f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.add_column(sa.Column('storage_path', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('storage_url',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=500),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.alter_column('storage_url',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('storage_path')

    # ### end Alembic commands ###
